abstract class AppConst {
  // static const String password = 'Passwprd';
  static const String aboutUs =
      'Welcome to our fitness app, where we are dedicated to\nempowering individuals on their journey to a healthier lifestyle.  we understand that every step toward fitness is unique, and our mission is to provide you with the tools, guidance, and motivation to reach your goals. Whether you\'re a seasoned athlete or just beginning your fitness journey, our user-friendly interface offers a seamless experience tailored to your needs. From personalized workout plans and nutrition tracking to community support and expert advice, we\'re here to support you every step of the way. Join us as we strive to inspire and transform lives through the power of fitness.';
  static const String privacyPolicy =
      '[Your Company/App Name] ("we", "us", or "our") operates the [Your App Name] mobile application (the "App"). This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our App and the choices you have associated with that data.We use your data to provide and improve the App. By using the App, you agree to the collection and use of information in accordance with this policy.Information Collection and UseWe collect several different types of information for various purposes to provide and improve our App.Types of Data CollectedPersonal DataWhile using our App, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:Email addressFirst name and last namePhone numberAddress, State, Province, ZIP/Postal code, CityCookies and Usage DataUsage DataWe may also collect information on how the App is accessed and used ("Usage Data"). This Usage Data may include information such as your device\'s Internet Protocol address';
  static const String termsAndConditions =
      'These Terms and Conditions ("Terms") govern your use of the [Your App Name] mobile application (the "App") operated by [Your Company Name] ("us", "we", or "our").By accessing or using the App, you agree to be bound by these Terms. If you disagree with any part of the terms, then you may not access the App.AccountsWhen you create an account with us, you must provide accurate, complete, and current information. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your account on our Service.You are responsible for safeguarding the password that you use to access the App and for any activities or actions under your password, whether your password is with our App or a third-party service.Intellectual PropertyThe App and its original content, features, and functionality are and will remain the exclusive property of [Your Company Name] and its licensors. The App is protected by copyright, trademark, and other laws of both [Your Country] and foreign countries. Our trademarks and trade dress may not be used in connection with any product or service without the prior written consent of [Your Company Name].TerminationWe may terminate or suspend access to our App immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.All provisions of the Terms which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity, and limitations of liability.';
  static const String cookiePolicy =
      '[Your Company Name] ("us", "we", or "our") operates the [Your App Name] mobile application (the "App").What Are CookiesCookies are small pieces of text sent by your web browser by a website you visit. A cookie file is stored in your web browser and allows the App or a third-party to recognize you and make your next visit easier and the App more useful to you.How We Use CookiesWhen you use and access the App, we may place a number of cookie files in your web browser.We use cookies for the following purposes:To enable certain functions of the AppTo provide analyticsTo store your preferencesThird-Party CookiesIn addition to our own cookies, we may also use various third-party cookies to report usage statistics of the App and deliver advertisements on and through the App.';
}
